---


- include_tasks: "{{ ansible_distribution }}-install.yml"
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "CentOS"
  tags:
    - install

- include_tasks: "{{ ansible_distribution }}-setup.yml"
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "CentOS"
  tags:
    - setup
